require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname,'../frontend')));
app.get('/', (req,res) => res.sendFile(path.join(__dirname,'../frontend/index.html')));
app.post('/api/chat', async (req,res)=>{ const {message}=req.body; res.json({reply:'Resposta simulada: '+message}); });
const PORT = process.env.PORT || 3000;
app.listen(PORT,()=>console.log('?? Server em http://localhost:'+PORT));
